### ISSUE TITLE
Undefined error with latest subsonic plugin

### ISSUE THREAD

**Issue by hndrewaall** [tomahawk-player/tomahawk-resolvers#120]
I am trying to run the latest subsonic plugin from source along with packaged 0.8.4 Tomahawk. I get this in the logs:

```Wed Jun 22 2016 - 16:49:20 [0]: JAVASCRIPT: "/Users/hndrewaall/personal/repos/tomahawk-resolvers/subsonic/content/contents/code/subsonic.js:0" "TypeError: 'undefined' is not a function" "undefined" ```

whenever I try to search. Any ideas?

**Comment by dschmidt** [comment]
Latest subsonic from master does not work with 0.8.4, try a nightly :-)
