### PR TITLE
Update Ampache/ownCloud resolver

### PR DESCRIPTION
**Pull request by dschmidt**
- resolver uses new promise based apis
- resolver should be more robust against session timeouts
- supports basic testConfig
- supports album view
- supports track view

### CODE REVIEW

**Comment by arthurlutz** [comment]
Am interrested in this being integrated into the official resolvers. Any particular reason why this is not being merged ?

**Comment by mrmaffen** [comment]
I'm currently working on that :)

**Comment by arthurlutz** [comment]
Will this new version work on 0.8.4 ? or do we need the (unpublished) 0.9.0 version ? 

am getting : 

```
09:01:25 [0]: JAVASCRIPT: "/home/arthur/local/tomahawk-resolvers/ampache/content/contents/code/ampache.js:1" "TypeError: 'undefined' is not a function (evaluating 'Tomahawk.resolver.instance.saveUserConfig()')" "undefined" 
```

**Comment by dschmidt** [comment]
@arthurlutz It's incompatible with 0.8.0. And even with master right now, I need to port tomahawk desktop to completely support this ... any help appreciated.

Find me on IRC (domme) if you want to help out
